### ISSUE TITLE
Some technical questions

### ISSUE THREAD

**Issue by qnzhou** [gcherchi/FastAndRobustMeshArrangements#11]
Hi Gianmarco,

Very nice work!  I have a few technical questions regarding the codebase:
1. It seems `solveIntersections` does not compute the topological info of the arrangement?  i.e. is it possible to extract cells from the output?
2. The output face label is a bitset of size 32.  Does it mean only 32 distinct labels are supported?  (I am thinking about using face ids as face labels, but the number of faces is almost certainly larger than 32.). I am also curious about the decision to use bitset instead of just `uint`, is it possible for an output triangle to have multiple source input triangles?
3. I noticed that the number of `genericPoint`s is more than the number of output vertices after `solveIntersections`, and there is a `-5` and a multiplier in the [exact-to-float conversion](https://github.com/gcherchi/FastAndRobustMeshArrangements/blob/master/code/processing.cpp#L146).  Can you explain a bit on what they are for?
4. I also noticed some degenerated triangles in the output (checked exactly with CGAL).  Is it expected?

Thanks a lot!
Qingnan Zhou

**Comment by gcherchi** [comment]
Hi Qingnan,
Thanks for your interest in our work. I'll answer you point by point:

1. the solve_intersection function is present in 4 different forms. In the out_tris parameter you have all the topological info about the output.
2. At the moment we have a limit of 32 distinct labels, but we are just releasing a version in which this number is templated. It is intended to represent the input mesh of each triangle, i.e., for boolean operations. In that case you can have a triangle belonging to multiple mesh (i.e. coplanar triangles).
3. You have 5 extra points in the genericPoints vector. 4 of them are to solve the problem discussed in section 5.4 and figure 9 of our paper, and 1 is to store a multiplier we compute and use to avoid underflow/overflow during the pipeline.
4. Yes, it is expected. This is a problem in common with the other arrangements works. It is known as snap rounding, and we discuss it in our paper, section 5.6. Basically, when you switch from the exact representation to an approximate one (double coorinates) you may map two different vertices in the same approximate coordinates, causing degenerate triangles.

**Comment by qnzhou** [comment]
Thanks Gianmarco!  Your answers make a lot of sense.  For 1, I am looking for ways to extract cells from the`out_tris`, do you have recommendation on how to do that?  For 4, the degenerate triangle I see is before snap rounding (i.e. I converted every `genericPoint` to a CGAL exact point and check for its degeneracy), but let me double check my code to ensure there is no bug in the conversion.

**Comment by gcherchi** [comment]
1. explain to me exactly what you would like to extract from out_tris
2. explain to me how you are converting genericPoints (most of them are represented implicitly as a combination of the original triangles) into CGAL exact points, so that I can check if that is a suitable pipeline.

**Comment by qnzhou** [comment]
Here is a 2D illustration of what I meant by extracting cells from the output:

![image](https://user-images.githubusercontent.com/3606672/105374826-1a75f880-5bd6-11eb-96c8-3a36fafc707b.png)

On the left side, we have 2 input squares.  After `solveIntersections`, we obtain a geometry with all intersections resolved (indicated by the new blue vertices in the mid figure).  In this simple case, the mesh arrangement of the input consists of 3 cells (as indicated by different color on the right figure).  My goal is to extract the faces associated with each cell.  Hope this is clear.

For 2, I converted `genericPoints` into CGAL points by computing the exact intersection between a line and a plane (if the point type is `LPI`) or the exact intersection between 3 planes (if the point type is `TPI`).  After some debug, I realize I did not set a compiler flag properly, fixing that seems to help.  I will let you know if I run into degeneracy issues again.

**Comment by gcherchi** [comment]
Ok, super clear. The actual algorithm does not provide this feature yet, but we are working on a new project that will include this feature. For now, we discuss a possible strategy to do that in our paper, on sec 5.5.

Good for point 2! Please, let me know if you find other dubious configurations.

Bests,
Gianmarco.

**Comment by qnzhou** [comment]
Thanks a lot for the clarification!  Closing this issue for now.
