### ISSUE TITLE
Can we track new triangle for source triangle?

### ISSUE THREAD

**Issue by ihsienlee** [gcherchi/FastAndRobustMeshArrangements#12]
I can set input data by triangles in STL file.
I can get new triangles by this software.
If I need to know each triangle from source triangle ID.
How can I do?

**Comment by gcherchi** [comment]
Hi, at the moment it is not possible. 
You can assign the label of the input mesh, but not of the single input triangle. Using a different label for each triangle is not supported at the moment. Extend the code in this sense is possible, but this would significantly slow down the pipeline.
