### ISSUE TITLE
Byte ambiguous symbol using Visual Studio 2019

### ISSUE THREAD

**Issue by diwot** [gcherchi/FastAndRobustMeshArrangements#17]
Hello, while trying to compile the code using Visual Studio 2019 I get an error telling me that byte is an ambiguous symbol. The error comes from a header in the windows SDK called rpcndr.h. I searched online, the error seems to be quite common when building for c++17 or higher but I was not able to find a solution yet to make the code compile. Was just wondering if anybody else is experiencing the same problem when building on Windows and if there is a known solution. The video shared on youtube looks very promising, so I'd really like to test the code :)

**Comment by mlivesu** [comment]
hi, a few days ago we added this code snippet at the beginning of the main
```
#ifdef _MSC_VER // Workaround for known bugs and issues on MSVC
#define _HAS_STD_BYTE 0  // https://developercommunity.visualstudio.com/t/error-c2872-byte-ambiguous-symbol/93889
#define NOMINMAX // https://stackoverflow.com/questions/1825904/error-c2589-on-stdnumeric-limitsdoublemin
#endif
```
Indeed, it was meant to avoid yours and other windows related symbol issues.
With this code we were able to build the code our windows machine.
Isn't this working for you?

**Comment by diwot** [comment]
I accidentally posted this issue in the wrong repo but the answer is still perfect. Adding those line at the beginning of main.cpp in mesh_booleans and in main-arap.cpp in mesh_booleans_arap in the mesh_booleans repo solves my issue. Thanks a lot
