### ISSUE TITLE
segfault on 996816.stl

### ISSUE THREAD

**Issue by sloriot** [gcherchi/FastAndRobustMeshArrangements#19]
Hi,

I'm using 0d9f2262acb4525bcf7dcf8a76047d9741ee84c8 on `Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux` with `g++ (Debian 12.2.0-14) 12.2.0` and trying to run `mesh_arrangement` on `996816.stl` lead to a segfault. Any idea what could be going wrong?

Disclaimer: I wanted to do a benchmark with @Brunolevy's code, yours and a new function I'm adding in CGAL, but it failed on the first file I tested.

```
> time ./mesh_arrangement Thingi10K/raw_meshes/996816.stl
Segmentation fault

real	4m7.636s
user	19m18.988s
sys	0m33.436s
```

**Comment by gcherchi** [comment]
Dear Sebastien,
Sorry for my late answer. 
First of all, thank you for your interest in our work. Please send me the model you are trying so that I can debug it.
Thanks,
Gianmarco

**Comment by sloriot** [comment]
It's the model https://ten-thousand-models.appspot.com/results.html?q=id%3A996816 from Thingi10K

**Comment by gcherchi** [comment]
Okay, that's the paper's teaser model.
That is undoubtedly the most complicated model of all Thingi10K. Consider that we did it with a machine with 128 GB of RAM (the computation requires at least 23) and at least 4 hours of time. We obtained the model we reported in the paper with these resources.
At the moment, I don't have the resources to re-test it, but without these resources, the code went into segmentation fault for us as well.
Could it be the problem also in your case?

**Comment by sloriot** [comment]
Nope, I do have 128GB and the memory consumption does not exceed a few GB before crashing

**Comment by gcherchi** [comment]
And the only message you obtain is "segmentation fault?" No warnings or other errore printed by the code?

**Comment by sloriot** [comment]
I posted everything that is on the console at the top of the issue. Do you want me to define an internal debug macro?

**Comment by gcherchi** [comment]
I'm trying to locate where the problem might be. The code we used for the experiments in the paper was "optimized" and made "header-only" before we published it on github. 
Also, when we wrote the paper on Booleans this code was heavily modified to make it faster. Maybe some bug was introduced in one of these steps. 
I was trying to locate the point in the computation where the code goes into segmentation fault.

**Comment by sloriot** [comment]
I just tried to compile in debug but it does not compile anymore.

```
FastAndRobustMeshArrangements.git/code/triangle_soup.h:42:10: fatal error: implicit_point.h: No such file or directory
   42 | #include <implicit_point.h>
      |          ^~~~~~~~~~~~~~~~~~
```

In my old build that header was in `_deps/indirect_predicates-src/implicit_point.h` but now it is in `_deps/indirect_predicates-src/include/implicit_point.h` (extra include). 

Is there something checkout'ed when building?

**Comment by gcherchi** [comment]
Yes, we have this problem since yesterday, following a major update of the indirect predicates repository. 
We are working to fix the problem as soon as possible.

**Comment by sloriot** [comment]
Hey, good news! After yesterday's updates, I was able to recompile and the segfault is no longer here! I guess the issue was in third party libraries then.

Side question: in `mesh_arrangement.cpp` are you also computing the arrangement or are you only doing the intersection resolution?

**Comment by gcherchi** [comment]
Fantastic!!
In mesh_arrangement.cpp, we just compute and solve the intersection between triangles (we do not compute the cells).

**Comment by BrunoLevy** [comment]
In case you are curious, [here is where this mesh comes from](https://www.instructables.com/3D-Printable-Large-Scale-Divers-Watch-Desk-Clock/) (smbdy on Twitter told me). But I don't know which operation / modelling package generated this mess....

**Comment by gcherchi** [comment]
Thank you @BrunoLevy 😊
