### ISSUE TITLE
Example file

### ISSUE THREAD

**Issue by petrasvestartas** [gcherchi/FastAndRobustMeshArrangements#2]
Hi,

I cloned and built the Visual Studio file 2019 x64 windows.

Can I ask to upload example file (meshes input)?
Do I need add something in Debug folder?

![image](https://user-images.githubusercontent.com/18013985/100546790-80dc3b80-3263-11eb-9f89-4e4148e2a020.png)

**Comment by mlivesu** [comment]
Hi, sample input files are indeed in the repo already. Check the `/data` folder, there are three input meshes that you can use for testing.

**Comment by petrasvestartas** [comment]
Could you please explain why .stl is still not found after copying to debug folder?

![image](https://user-images.githubusercontent.com/18013985/100624068-433ee780-3323-11eb-8731-4814eca69f2f.png)

**Comment by mlivesu** [comment]
You seem to have problems with your relative paths. This is not related to our tool, I am closing the issue.
My personal suggestion is that you compile the code without hardcoding any input, and you just call the executable from your shell, passing a proper input file (e.g. the ones we included in the repo).

**Comment by petrasvestartas** [comment]
I would like to learn how to use it properly via Visual Studio.

Since it is a first step, can you advise me how to fix "relative paths"?

After typing the full path:
`	std::string file_in = "C:\\libs\\FastAndRobustMeshArrangements\\build\\Debug\\two_spheres.stl";`
 I get this error:

![image](https://user-images.githubusercontent.com/18013985/100638333-31b20b80-3334-11eb-82f7-e2a0db850ab3.png)
