### ISSUE TITLE
General instability on complex meshes

### ISSUE THREAD

**Issue by proc-sim** [gcherchi/FastAndRobustMeshArrangements#22]
I've been testing this library but it is really difficult to get error-free output, once meshes become more complex than simple intersecting spheres, cubes, etc. My input meshes do not have degeneracies...just many intersections.

The assertions I run into over and over happen exclusively during the triangulation phase. 

For example, the attached mesh generates an assertion on line 735 of fast_trimesh.cpp. According to my debugger when the assertion is hit, "t_id" has some impossible value (3722304989), and I think it's because the e2t vector is being modified inside the for loop (by addTri), thus invalidating the vector iterator of the loop itself if any reallocations of the vector occur (that's my guess). If I iterate a copy of the e2t vector instead of e2t directly, I no longer get an assertion (however the triangulation function fails elsewhere instead).

I'll avoid posting dozens of other meshes with similar issues (there are a few key places like this where assertions keep firing), but overall it seems like the triangulation function is problematic. 

I'm compiling on Windows using VS 2019, C++ 17.

I also understand this library is no longer maintained, but I'm posting the bug report anyways in case any else solves the issue(s).

[testOpB.zip](https://github.com/gcherchi/FastAndRobustMeshArrangements/files/12653356/testOpB.zip)

**Comment by sloriot** [comment]
Did you try triangulating your input first?

**Comment by gcherchi** [comment]
Dear @t-i-dev , 
as we acknowledged in the disclaimer in the main page we are aware that our code contains bugs but we currently have no resources to put a student on this project and improve reliability. We know for sure that the extreme parallelization that we applied for the interactive booleans project has introduced memory issues, and we are considering switching back to the previous (less parallel) version.

That being said, please, before opening a public issue titled "General instability on complex meshes", declaring that the code fails on dozens of meshes, read the paper to understand how to use it. Our algorithm works on triangles, while your input is a quadrilateral mesh. As @sloriot rightly points out, you need to triangulate your input before passing it to our code.

I tried the computation with your "triangulated" input and no crashes were reported.

**Comment by proc-sim** [comment]
Hi @gcherchi and @sloriot, 

Thank you for the quick response. The simple difference (a triangulated .obj vs a quadrangulated .obj) does indeed solve the problem on the meshes I was testing. I apologize for jumping to conclusions, @gcherchi...it was not my intention to denigrate your work...the general .obj format compatibility of the library led me to believe that I would not need to preprocess my exported meshes first. I didn't even realize that .obj exported quads until you mentioned it.
