### ISSUE TITLE
Directory fails

### ISSUE THREAD

**Issue by petrasvestartas** [gcherchi/FastAndRobustMeshArrangements#3]
Hi,

This is related to previous issue.

I would like to learn how to use your project properly via Visual Studio.

Since it is a first step, can you advise me how to fix "relative paths"?

After typing the full path:
std::string file_in = "C:\\libs\\FastAndRobustMeshArrangements\\build\\Debug\\two_spheres.stl";

I get this error:

![image](https://user-images.githubusercontent.com/18013985/100659136-78156380-3350-11eb-9b2c-779b96242b0c.png)

**Comment by gcherchi** [comment]
Hi,
in the file main.cpp delete all lines from 48 to 58 and replace them with:
std::string file_in = "absolute/path/to/your/file.stl";
I'm closing this issue. If you have other doubts about paths please contact us via e-mail, without open any other issues.
