### ISSUE TITLE
Remove interior geometry?

### ISSUE THREAD

**Issue by mdmaas** [gcherchi/FastAndRobustMeshArrangements#5]
Hi! First let me say that I am so glad to have found your paper and this code. I'm new to computational geometry, and I feel that your code might be the first step in getting me anywhere near of what I would like to do as a research project at some point in the future, which is  re-meshing of triangulated (not necessarily closed) surfaces with curved elements to the highest possible order. 

In any case, I was wondering if you envision to include in this project a feature that seems to me like a logical next step regarding the fixing of a triangulated surface mesh (the removal of the interior triangles) or if you do not want to expand the extent of this code any further.

Maybe with a little guidance from your side I could implement such a feature. The way I would approach the problem (remember I'm not an expert in comp-geom) would simply be, for each triangle, to count the number of intersections from a ray that has an origin in it's barycenter with the rest of the mesh. This should be done with an octree for efficiency. What I'm not sure about is on how to produce a robust approach for this problem. My naive attempt would be to use a non-robust test like Moller-Trumbore and just cast an other ray in a random direction should any of the intersection tests return a number close to zero.

Some useful function to implement this I have found is Cinolib::Octree::intersects_ray, and there is also the Moller-Trumbore algorithm in Cinolib. Hopefully with those two functions I should be able to get something done. I am a little puzzled right now on how to use the "all_hits" output from the octree (items.at(i)->id), but maybe if I run some tests I could track the indices of the triangle mesh to the ids in the octree.

I would kindly appreciate any advice on this matter!

Regards,
Martín

**Comment by gcherchi** [comment]
Hi Martin,
thank you for your interest in our work.
We are already working on solving this problem in an exact way. Stay tuned.
Bests,
Gianmarco.

**Comment by mlivesu** [comment]
Hi Martín, thanks for the super nice feedback :)

As Gianmarco said we are currently working on this issue, and the goal is to make everything exact using our robust predicates. I strongly suggest not to use Moller-Trumbore for this purpose: when the ray and a triangle are nearly parallel the algorithm becomes extremely unstable...

For the question on the Octree in my library: indeed items.at(i)->id is the id of the triangle in the mesh from which you generated the octree, so you can use those numbers to track intersected elements in your mesh

**Comment by mdmaas** [comment]
Dear Marco and Gianfranco, 

Great to know this is coming down the road! You have a big fan here! I have also run some of the examples of your library Cinolib, and I have found your code very clear and user-friendly, so I guess I will be sticking with it.

Regards!
