### ISSUE TITLE
[Question] Clang's IEEE 754 compliance

### ISSUE THREAD

**Issue by artem-ogre** [gcherchi/FastAndRobustMeshArrangements#8]
Dear @gcherchi ,

Thank you for this interesting work and for using a nice permissive license for the code! I wish more computational geometry research (especially state-funded) was published this way :)

I am curious about this quote from the readme:
> WARNING: Apparently, CLANG does not support a fully IEEE compliant floating point environment. The only way we found to guarantee correctness on this compiler was to disable all optimizations. Please be aware of this fact should you notice a performance degradation in your experiments.

Could you provide more details about this? Maybe some links or explanations to educate myself about this problem?

**Comment by gcherchi** [comment]
Hi, 
When we checked, clang did not provide a sufficiently complete access to the floating point environment (i.e. to properly set the rounding mode). This is a known problem (i.e. https://www.boost.org/doc/libs/1_69_0/libs/numeric/interval/doc/interval.htm)
We are doing some experiment to check if the problem has been solved in the last version.

**Comment by artem-ogre** [comment]
I see, thanks for the answer. So it was a proper support of `frounding-math` that was missing in clang? Quick googling shows that [clang 10 should support it](https://releases.llvm.org/10.0.0/tools/clang/docs/ClangCommandLineReference.html#cmdoption-clang-frounding-math) :)

**Comment by gcherchi** [comment]
Yes, we saw it some time ago, but it's not true. Clang supports frounding-math in the sense that it does not give an error, but the flag is completely ignored. There is also a compiler warning confirming it: warning: optimization flag '-frounding-math' is not supported [-Wignored-optimization-argument].
We did several tests in the past days, and we found the only way to "fix" the problem is compiling with -O0.

**Comment by artem-ogre** [comment]
Oh, that is nice to know. Thank you for the explanation.

**Comment by starseeker** [comment]
Last discussion of the issue looks like it was here:  https://reviews.llvm.org/D62731

It sounds like they need some internal improvements before they'd be able to properly achieve what that flag would need...  Maybe if this library (is there an approved "shorthand" name for it, by the way?  FRMA or libfrma?) starts to be used more widely, the pressure will mount to sort it out.
